# Copyright 2020 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
settings:
  name: generic-kubernetes
  min_similarity: 0.8
  repos:
    - https://github.com/kubernetes/community

  # Who should automatically be considered a project member?
  # See: https://developer.github.com/v4/enum/commentauthorassociation/
  # Default is "collaborator, owner, member", unless "members" is set
  #
  #member-roles:
  # - collaborator
  # - owner
  # - member
  # Who else do we consider to be a project member? Default is empty.
  #members:
  # - tstromberg

collections:
  - id: daily
    name: Daily Triage
    dedup: true
    description: >
      queue to be emptied once a day
    rules:
      - issue-needs-priority-overdue
      - issue-needs-comment-overdue
      - issue-soon-overdue
      - issue-longterm-overdue
      # Don't leave code reviews hanging
      - pr-reviewable
      # missing initial feedback
      - issue-needs-kind
      - issue-needs-priority
      - issue-needs-comment
      # reprioritize
      - issue-new-with-reactions
      - issue-new-with-many-commenters
      # Don't forget our users
      - issue-updated-needs-info
      - issue-updated-has-question

  - id: weekly
    name: Weekly Triage
    dedup: true
    description: >
      queue to be emptied once a week in a team triage meeting
    rules:
      # SLO
      - issue-near-soon-overdue
      - issue-near-longterm-overdue
      # Issues needing reprioritization
      - many-reactions
      - many-commenters
      - issue-zombies
      # Issues needing closure
      - issue-stale-needs-info
      - issue-stale-support
      - lifecycle-rotten
      # PR's needing closure
      - pr-approved-stale
      - pr-unapproved-stale
      # People with questions
      - issue-has-question
      - issue-updated-support

  - id: milestone
    name: In Milestone
    description: >
      A Kanban visualization of milestones, showing the flow of issues through each stage.

        * Unassigned issues represent available work
        * >3 issues assigned to the same person within a stage signifies a bottleneck ðŸŒŠ
    display: kanban
    overflow: 3
    dedup: true
    rules:
      - milestone-not-started
      - milestone-assignee-updated
      - milestone-pr-needs-review
      - milestone-pr-needs-work
      - milestone-pr-needs-merge
      - milestone-recently-closed

  - id: scrub
    name: Quarterly Scrub
    dedup: true
    description: Once every quarter, look for stale issues, reprioritize, and de-duplicate.
    rules:
      - lifecycle-stale
      - features-old-recv
      - features-old
      - bugs-old-recv
      - bugs-old
      - other-old-recv
      - other-old

  - id: recv
    name: "Receive queue"
    description: >
      Issues that may be waiting for our response

      NOTE: for this to work properly, GitHub token must have read access to read organization members
    rules:
      - question-recv
      - bugs-recv
      - enhancement-recv
      - other-recv

  - id: important
    name: Important
    description: >
      Items labeled as priority/important-soon or priority/critical-urgent.
    overflow: 3
    dedup: true
    rules:
      - important-not-milestoned
      - important-milestoned
      - important-assignee-updated
      - important-pr-needs-review
      - important-pr-needs-work
      - important-pr-needs-merge
      - important-recently-closed

  - id: similar
    name: Similar
    description: Items which appear similar to one other. Review for duplicates or vague titles.
    rules:
      - similar-prs
      - similar-issues

  - id: __open__
    name: All open PR's and Issues that should be considered for repository stats (hidden)
    used_for_statistics: true
    hidden: true
    rules:
      - open-prs
      - open-issues

  - id: __velocity__
    name: issues to include in velocity metrics
    used_for_statistics: true
    hidden: true
    rules:
      - closed-milestone-issues

rules:
  ### Daily Triage ####
  issue-needs-priority-overdue:
    name: "Unprioritized issues older than 7 days"
    resolution: "Add a priority/ or triage/ label"
    type: issue
    filters:
      - label: "!priority/.*"
      - label: "!triage/.*"
      - created: +7d

  issue-needs-comment-overdue:
    name: "Uncommented older than 7 days"
    resolution: "Add a priority/ or triage/ label"
    type: issue
    filters:
      - tag: "!commented"
      - tag: "recv"
      - created: +7d

  issue-soon-overdue:
    name: "Important soon, but no updates in 90 days"
    resolution: "Downgrade to important-longterm"
    type: issue
    filters:
      - label: "priority/important-soon"
      - updated: +90d

  issue-longterm-overdue:
    name: "Important longterm, but no updates in 180 days"
    resolution: "Downgrade to backlog"
    type: issue
    filters:
      - label: "priority/important-longterm"
      - updated: +180d

  # Don't leave code reviews hanging
  pr-reviewable:
    name: "Pull Requests: Review Ready"
    resolution: "Review requests or mark them as do-not-merge/work-in-progress"
    type: pull_request
    filters:
      - label: "!do-not-merge.*"
      - label: "!needs-rebase"
      - label: "!cncf-cla: no"
      - tag: "!changes-requested"
      - tag: "!send"

  # Issues missing initial feedback
  issue-needs-kind:
    name: "Unkinded Issues"
    resolution: "Add a kind/ or triage/support label"
    type: issue
    filters:
      - label: "!kind/.*"
      - label: "!triage/support"

  issue-needs-priority:
    name: "Unprioritized Recent Issues"
    resolution: "Add a priority/ or triage/ label"
    type: issue
    filters:
      - label: "!priority/.*"
      - label: "!triage/.*"

  issue-needs-comment:
    name: "Uncommented Recent Issues"
    resolution: "Add a comment"
    type: issue
    filters:
      - tag: "!commented"
      - tag: "recv"
      - created: -7d

  # Issues that may need reprioritized
  issue-new-with-reactions:
    name: "New, has multiple reactions, but not important-soon"
    resolution: "Check if issue should be prioritized as important-soon"
    type: issue
    filters:
      - reactions: ">2"
      - created: -10d
      - tag: "!send"
      - label: "!priority/important-soon"

  issue-new-with-many-commenters:
    name: "New, has multiple commenters, but not important-soon"
    resolution: "Check if issue should be prioritized as important-soon"
    type: issue
    filters:
      - commenters: ">3"
      - created: -10d
      - tag: "!send"
      - label: "!priority/important-soon"

  # Don't forget our users
  issue-updated-needs-info:
    name: "needs information, has update"
    resolution: "Comment and remove triage/needs-information tag"
    type: issue
    filters:
      - label: triage/needs-information
      - tag: recv

  issue-updated-has-question:
    name: "Recently updated issue has a question"
    resolution: "Add an answer"
    type: issue
    filters:
      - tag: recv-q
      - label: "!triage/needs-information"
      - tag: "!member-last"
      - tag: "!contributor-last"
      - responded: +3d
      - updated: -7d

  ####### Weekly Triage #########
  # SLO nearing
  issue-near-soon-overdue:
    name: "Important soon, but no updates in 60 days"
    resolution: "Downgrade to important-longterm"
    type: issue
    filters:
      - label: "priority/important-soon"
      - updated: +60d

  issue-near-longterm-overdue:
    name: "Important longterm, but no updates in 120 days"
    resolution: "Downgrade to backlog"
    type: issue
    filters:
      - label: "priority/important-longterm"
      - updated: +120d

  # issues needing reprioritization
  many-reactions:
    name: "many reactions, low priority"
    resolution: "Upgrade to priority-soon, priority-longterm, or longterm-support"
    filters:
      - reactions: ">3"
      - reactions-per-month: ">0.75"
      - label: "!priority/important-soon"
      - label: "!priority/important-longterm"
      - label: "!long-term-support"

  many-commenters:
    name: "many commenters, low priority"
    resolution: "Upgrade to priority-soon, priority-longterm, or longterm-support"
    filters:
      - commenters: ">2"
      - commenters-per-month: ">1.9"
      - created: "+30d"
      - label: "!priority/important-soon"
      - label: "!priority/important-longterm"
      - label: "!long-term-support"

  issue-zombies:
    name: "Screaming into the void"
    resolution: "Reopen, or ask folks to open a new issue"
    type: issue
    filters:
      - state: closed
      - updated: -7d
      - tag: recv
      - comments-while-closed: ">1"

  # Issues needing closure
  issue-stale-needs-info:
    name: "Needs information for over 2 weeks"
    resolution: "Close or remove triage/needs-information label"
    type: issue
    filters:
      - label: triage/needs-information
      - updated: +13d

  issue-stale-support:
    name: "Support request over 30 days old"
    resolution: "Close, or add to triage/long-term-support"
    type: issue
    filters:
      - label: triage/support
      - label: "!long-term-support"
      - updated: +29d

  lifecycle-rotten:
    name: "Issues nearing expiration"
    resolution: "Close or label as frozen"
    filters:
      - label: lifecycle/rotten

  # PR's needing closure
  pr-approved-stale:
    name: "Pull requests: Approved and getting old"
    type: pull_request
    filters:
      - label: "!do-not-merge.*"
      - label: "!needs-rebase"
      - label: "approved"
      - updated: +5d

  pr-unapproved-stale:
    name: "Pull Requests: Stale"
    resolution: "Add comment and/or close PR"
    type: pull_request
    filters:
      - created: +20d
      - updated: +5d

  # People with questions
  issue-has-question:
    name: "Overdue answers for a question"
    resolution: "Add a comment"
    type: issue
    filters:
      - tag: recv-q
      - label: "!triage/needs-information"
      - tag: "!member-last"
      - tag: "!contributor-last"
      - responded: +6d

  issue-updated-support:
    name: "Updated support requests"
    resolution: "Move out of support, or add a comment"
    type: issue
    filters:
      - tag: recv
      - label: "!triage/needs-information"
      - tag: "!member-last"
      - tag: "!contributor-last"
      - responded: +6d

  ### Milestone Kanban ###
  milestone-not-started:
    name: "Not started"
    type: issue
    filters:
      - tag: open-milestone
      - tag: "!assignee-updated"
      - tag: "!(assignee-open-pr|assignee-closed-pr)"
  milestone-assignee-updated:
    name: "In Progress"
    type: issue
    filters:
      - tag: open-milestone
      - tag: "assignee-updated"
      - tag: >-
         !(
         pr-changes-requested|
         pr-reviewer-comment|
         pr-unreviewed|
         pr-new-commits|
         pr-approved|
         pr-changes-requested
         )
  milestone-pr-needs-work:
    name: "PR needs work"
    type: issue
    filters:
      - tag: open-milestone
      - tag: "(pr-changes-requested|pr-reviewer-comment)"
  milestone-pr-needs-review:
    name: "PR needs Review"
    type: issue
    filters:
      - tag: open-milestone
      - tag: "(pr-unreviewed|pr-new-commits)"
  milestone-pr-needs-merge:
    name: "PR needs Merge"
    type: issue
    filters:
      - tag: open-milestone
      - tag: "(pr-approved|pr-approved-but-pushed)"
  milestone-recently-closed:
    name: "Finish Line"
    type: issue
    filters:
      - tag: open-milestone
      - state: closed
      - updated: -30d

  ## Bug Scrub ##
  bugs-old-recv:
    name: "Bugs that deserve a follow-up comment"
    resolution: "Comment or close the issue"
    type: issue
    filters:
      - tag: recv
      - responded: +60d
      - created: +60d
      - label: "kind/bug"

  features-old-recv:
    name: "Features that deserve a follow-up comment"
    resolution: "Comment or close the issue"
    type: issue
    filters:
      - tag: recv
      - responded: +90d
      - created: +30d
      - label: "kind/feature"

  other-old-recv:
    name: "Items that deserve a follow-up comment"
    resolution: "Comment or close the issue"
    type: issue
    filters:
      - tag: recv
      - responded: +60d
      - label: "!kind/feature"
      - label: "!kind/bug"
      - label: "!triage/support"

  features-old:
    name: "Features that have not been commented on within 90 days"
    resolution: "Comment or close the issue"
    type: issue
    filters:
      - responded: +90d
      - created: +90d
      - label: "kind/feature"

  bugs-old:
    name: "Bugs that have not been commented on within 60 days"
    resolution: "Comment or close the issue"
    type: issue
    filters:
      - label: "kind/bug"
      - responded: +60d
      - created: +60d
      - label: "!priority/awaiting-evidence"

  other-old:
    name: "Items that have not been commented on within 60 days"
    resolution: "Comment or close the issue"
    type: issue
    filters:
      - responded: +90d
      - created: +90d
      - label: "!kind/feature"
      - label: "!kind/bug"
      - label: "!triage/support"
      - label: "!priority/awaiting-evidence"

  lifecycle-stale:
    name: "Issues nearing expiration"
    resolution: "Close or label as frozen"
    filters:
      - label: lifecycle/stale

  # Receive queue
  question-recv:
    name: "Questions awaiting follow-up"
    resolution: "Comment or close the issue"
    type: issue
    filters:
      - tag: recv
      - label: ".*question"

  bugs-recv:
    name: "Bugs awaiting follow-up"
    resolution: "Comment or close the issue"
    type: issue
    filters:
      - tag: recv
      - label: ".*bug"

  enhancement-recv:
    name: "Features awaiting follow-up"
    resolution: "Comment or close the issue"
    type: issue
    filters:
      - tag: recv
      - label: ".*(feature|enhancement|idea).*"

  other-recv:
    name: "Items that deserve a follow-up comment"
    resolution: "Comment or close the issue"
    type: issue
    filters:
      - tag: recv
      - responded: +30d
      - label: "!.*(feature|enhancement).*"
      - label: "!.*bug"
      - label: ".*question"

  ### Important Kanban ###
  important-not-milestoned:
    name: "Not in milestone"
    type: issue
    filters:
      - label: "priority/important-soon|priority/critical-urgent"
      - tag: "!open-milestone"
      - tag: "!assignee-updated"
      - tag: "!(assignee-open-pr|assignee-closed-pr)"
  important-milestoned:
    name: "In Milestone"
    type: issue
    filters:
      - label: "priority/important-soon|priority/critical-urgent"
      - tag: open-milestone
      - tag: >-
         !(
          pr-changes-requested|
          pr-reviewer-comment|
          pr-unreviewed|
          pr-new-commits|
          pr-approved|
          pr-changes-requested|
          assignee-updated
          )
  important-assignee-updated:
    name: "In Progress"
    type: issue
    filters:
      - label: "priority/important-soon|priority/critical-urgent"
      - tag: "assignee-updated"
      - tag: "!(pr-changes-requested|pr-reviewer-comment|pr-unreviewed|pr-new-commits|pr-approved|pr-changes-requested)"
  important-pr-needs-work:
    name: "PR needs work"
    type: issue
    filters:
      - label: "priority/important-soon|priority/critical-urgent"
      - tag: "(pr-changes-requested|pr-reviewer-comment)"
  important-pr-needs-review:
    name: "PR needs Review"
    type: issue
    filters:
      - label: "priority/important-soon|priority/critical-urgent"
      - tag: "(pr-unreviewed|pr-new-commits)"
  important-pr-needs-merge:
    name: "PR needs Merge"
    type: issue
    filters:
      - label: "priority/important-soon|priority/critical-urgent"
      - tag: "(pr-approved|pr-approved-but-pushed)"
  important-recently-closed:
    name: "Recently closed"
    type: issue
    filters:
      - label: "priority/important-soon|priority/critical-urgent"
      - state: closed
      - updated: -30d

  ## Similar
  similar-prs:
    name: "Similar Pull Requests"
    type: pull_request
    resolution: Close as duplicate or give a better title
    filters:
      - tag: similar

  similar-issues:
    name: "Similar Issues"
    type: issue
    resolution: Close as duplicate or give a better title
    filters:
      - tag: similar

  # for statistics generation
  open-issues:
    name: "Open Issues"
    type: issue

  open-prs:
    name: "Open PRs"
    type: pull_request

  closed-milestone-issues:
    name: "Recently closed milestone issues"
    type: issue
    filters:
      - state: closed
      - closed: -90d
      - milestone: ".*"
      - label: "!triage/duplicate"
